# Generated by Django 5.0 on 2023-12-27 23:40

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_company_notes_alter_company_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_start_date', models.DateTimeField(blank=True, null=True)),
                ('task_due_date', models.DateTimeField(blank=True, null=True)),
                ('task_complete', models.BooleanField(default=False)),
                ('task_notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateField(default=django.db.models.functions.datetime.Now())),
                ('apply_notes', models.TextField(null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.role')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_title', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=254, null=True)),
                ('contact_phone', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.company')),
            ],
        ),
    ]
