# Generated by Django 5.0 on 2023-12-28 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_task_role_responsibilities_application_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.contact'),
        ),
    ]
